---

#- include_tasks: "{{ playbook_dir }}/roles/common/tasks/os_set_hostname.yml"

#- include_tasks: "{{ playbook_dir }}/roles/common/tasks/os_disable_firewalld.yml"

#- include_tasks: "{{ playbook_dir }}/roles/common/tasks/os_configure_iptables.yml"

- include_tasks: "{{ playbook_dir }}/roles/common/tasks/os_configure_etc_hosts.yml"

- include_tasks: "{{ playbook_dir }}/roles/common/tasks/create_user_group.yml"

- include_tasks: "{{ playbook_dir }}/roles/common/tasks/configure_thp.yml"

- include_tasks: "{{ playbook_dir }}/roles/common/tasks/configure_ulimits.yml"

- include_tasks: "{{ playbook_dir }}/roles/common/tasks/check_splunk_installed.yml"

- include_tasks: "{{ playbook_dir }}/roles/common/tasks/copy_splunk_package_file.yml"

- include_tasks: "{{ playbook_dir }}/roles/common/tasks/install_splunk.yml"

- include_tasks: "{{ playbook_dir }}/roles/common/tasks/check_splunkd_status.yml"

- include_tasks: "{{ playbook_dir }}/roles/common/tasks/create_system_local_user_seed.yml"

- include_tasks: "{{ playbook_dir }}/roles/common/tasks/disable_first_time_password_prompt.yml"

- include_tasks: "{{ playbook_dir }}/roles/common/tasks/configure_splunk_boot_start.yml"

- include_tasks: "{{ playbook_dir }}/roles/common/tasks/create_certificates.yml"

- include_tasks: "{{ playbook_dir }}/roles/common/tasks/create_system_local_server.yml"

- include_tasks: "{{ playbook_dir }}/roles/common/tasks/create_system_local_web.yml"

- include_tasks: "{{ playbook_dir }}/roles/common/tasks/configure_password_policy.yml"

- include_tasks: "{{ playbook_dir }}/roles/common/tasks/create_system_local_outputs.yml"
  when:
    - 'ansible_host in groups["search_head"] or ansible_host in groups["license_master"] or ansible_host in groups["monitoring_console"] or ansible_host in groups["cluster_master"] or ansible_host in groups["deployment_server"] or ansible_host in groups["deployer"]'

- include_tasks: "{{ playbook_dir }}/roles/common/tasks/create_system_local_inputs.yml"
  when:
    - '"indexer" in groups'
    - 'ansible_host in groups["indexer"]'

- include_tasks: "{{ playbook_dir }}/roles/common/tasks/disable_webui.yml"
  when:
    - '"indexer" in groups'
    - 'ansible_host in groups["indexer"]'

- include_tasks: "{{ playbook_dir }}/roles/common/tasks/disable_monitoring_console.yml"
  when:
    - '"monitoring_console" in groups'
    - 'ansible_host not in groups["monitoring_console"]'

- include_tasks: "{{ playbook_dir }}/roles/common/tasks/start_splunk.yml"

- include_tasks: "{{ playbook_dir }}/roles/common/tasks/disable_popup.yml"

- include_tasks: "{{ playbook_dir }}/roles/common/tasks/delete_splunk_installer.yml"

#- include_tasks: "{{ playbook_dir }}/roles/common/tasks/delete_system_local_user_seed.yml"

- include_tasks: "{{ playbook_dir }}/roles/common/tasks/restart_splunk.yml"

