---

- name: Check if shclustering is enabled
  shell: "echo $({{ splunk.home }}/bin/splunk list shcluster-config -auth {{ splunk.admin.username }}:{{splunk.admin.password}} | egrep -e 'disabled:0')"
  become: true
  become_user: "{{ splunk.nix.user }}"
  register: cm_shclustering_enabled
  failed_when: "cm_shclustering_enabled.rc > 1"

