---

#4.1 - Configure Splunk to use AD for authentication and authorization 

- name: "4.1 - Check that authentication.conf exists"
  become: true
  become_user: "{{ splunk.nix.user }}"
  stat:
    path: "{{ splunk.home }}/etc/system/local/authentication.conf"
  register: auth_conf
  
- name: "[Results] 4.1 - Check that authentication.conf exists"  
  fail:
    msg: "Authentication.conf not found!"
  when: auth_conf.stat.exists == False
  ignore_errors: true
  
#If configuration is changed, line does not exists in file. Failing audit test.
- name: "4.1 - Check that authType = ldap"
  lineinfile:
    path: "{{ splunk.home }}/etc/system/local/authentication.conf"
    line: "authType = LDAP"
    state: present
  check_mode: yes
  register: authType
  when: auth_conf.stat.exists

- name: "[Results] 4.1 - Check that authType = ldap"
  fail:
    msg: "AuthType not found!"
  when: 
    - authType is changed
    - auth_conf.stat.exists
  ignore_errors: true
  
- name: "[Results] 4.1 - Check that authType = ldap"
  debug:
    msg: "Passed! authType = LDAP"
  when: 
    - authType is not changed
    - auth_conf.stat.exists   