---
# 3. Password Management

# 3.1 Configure Splunk password policies

- name: "3.1 Run the below search string to verify that Splunk password policies has been configured"
  become: true
  become_user: "{{ splunk.nix.user }}"
  shell: "{{ splunk.home }}/bin/splunk btool authentication list --debug | egrep 'splunk_auth |'"
  register: passwordPol
  ignore_errors: true
  when:
    - "'search_head' in group_names"
  
- name: "[Results] 3.1 Run the below search string to verify that Splunk password policies has been configured"
  debug:
    msg: "{{ passwordPol.stdout.split('\n') }}"
  ignore_errors: true
  when:
    - "'search_head' in group_names"

##########################################################################################################################################################################

#### 3.3 Password encrypted during transit

- name: "3.3 Run the below search string to verify that Splunk password is encrypted during transit"
  become: true
  become_user: "{{ splunk.nix.user }}"
  shell: "{{ splunk.home }}/bin/splunk btool web list --debug | grep -i 'enableSplunkWebSSL'"
  register: passwordEncr
  ignore_errors: true
  when:
    - "'search_head' in group_names"
  
- name: "[Results] 3.3 Run the below search string to verify that Splunk password is encrypted during transit"
  debug:
    msg: "{{ passwordEncr.stdout.split('\n') }}"
  ignore_errors: true
  when:
    - "'search_head' in group_names"

##########################################################################################################################################################################
