---

#- name: Ensure repo is in /etc/hosts
#  lineinfile:
#    dest: /etc/hosts
#   regexp: "^{{ ansible_default_ipv4.address }}.+$"
#    line: "{{ base.repo.host }} {{ base.repo.suffix }} {{ base.repo.suffix }}.{{ base.repo.fqdn }}"

- name: Ensure hostname is in /etc/hosts
  become: true
  lineinfile:
      dest: /etc/hosts
      regexp: '.*{{ item }}$'
      line: "{{item}} {{ hostvars[item].host_suffix }} {{ hostvars[item].host_suffix }}.{{ hostvars[item].base.fqdn }} {{item}}"
      state: present
  with_items: "{{ groups.all }}"

