---

- name: Configure password policy
  become: true
  become_user: "{{ splunk.nix.user }}"
  ini_file:
    dest: "{{ splunk.home }}/etc/system/local/authentication.conf"
    section: "{{ item.section }}"
    option: "{{ item.key }}"
    value: "{{ item.value }}"
    owner: "{{ splunk.nix.user }}"
    group: "{{ splunk.nix.group }}"
  with_items:
    - {section: "splunk_auth", key: "enablePasswordHistory", value: "1"}
    - {section: "splunk_auth", key: "passwordHistoryCount", value: "3"}
    - {section: "splunk_auth", key: "enablePasswordHistory", value: "1"}
    - {section: "splunk_auth", key: "expirePasswordDays", value: "365"}
    - {section: "splunk_auth", key: "expireUserAccounts", value: "1"}
    - {section: "splunk_auth", key: "lockoutUsers", value: "1"}
    - {section: "splunk_auth", key: "lockoutMins", value: "15"}
    - {section: "splunk_auth", key: "minPasswordLength", value: "12"}
    - {section: "splunk_auth", key: "minPasswordLowercase", value: "1"}
    - {section: "splunk_auth", key: "minPasswordSpecial", value: "1"}
    - {section: "splunk_auth", key: "minPasswordUppercase", value: "1"}
    - {section: "splunk_auth", key: "minPasswordDigit", value: "1"}
  register: password_policy_configured
