---

- name: Check if expansion peer joined cluster
  shell: "{{ splunk.home }}/bin/splunk list peer-info -auth {{ splunk.admin.username }}:{{ splunk.admin.password }} | grep Up"
  register: expansion_peer_status
  become: true
  become_user: "{{ splunk.nix.user }}"
  when: "'expansion_indexer' in group_names"
  failed_when: "expansion_peer_status.rc == 1"
  changed_when: "expansion_peer_status.rc == 0"
  retries: 3
  delay: 3
  until: expansion_peer_status.rc == 0
