---

- name: Restart splunk
  become: true
  become_user: "{{ splunk.nix.user }}"
  command: "{{ splunk.home }}/bin/splunk restart"
  retries: 5
  delay: 30
  register: result
  until: result.rc == 0
  when: splunk.systemd != 'true'

- name: Restart splunk - systemd
  become: true
  systemd:
    name: Splunkd
    state: restarted
    enabled: yes
  when: splunk.systemd == 'true'

- include_tasks: "{{ playbook_dir }}/roles/common/tasks/base_os_wait_for_splunk_instance.yml"
  vars:
    splunk_instance: "{{ ansible_host }}"
  when:    
    - "'universal_forwarder' not in group_names"


